# Generated by Django 4.1.6 on 2023-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0005_delete_variationmanager'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='appStore.variation'),
        ),
    ]
