# Generated by Django 4.1.6 on 2023-06-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
    ]
