# Generated by Django 4.1.6 on 2023-05-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0004_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
